### PR TITLE
Fix improvement and cleanup for init

### PR DESCRIPTION
**Pull request by LKHN**
* Fixed installed package number inconsistency when building on
  different enivorments: KVM:193,AWS:191:VMware:192,ks2rootfs:192
* Removed subscription-manager and its dependencies. Installed
  package count is 166 now
* Cleanup: The image size reduced to 212MB

Signed-off-by: Elkhan Mammadli <elkhan.mammadli@protonmail.com>

### CODE REVIEW

**Comment by srbala** [comment]
@LKHN some of the packages added to be 1:1 UBI series. @ezamriy can we trim packages?

**Comment by LKHN** [comment]
> @LKHN some of the packages added to be 1:1 UBI series. @ezamriy can we trim packages?

Some or subscription-related ones? the second trimmed only :thinking:

**Comment by ezamriy** [comment]
That subscription-manager issue is tricky. At the first look it is not needed at all and we removed it in some first beta of AlmaLinux itself. But it is required if a user is using Foreman/Katello which are pretty popular.

So, the answer depends on what our user is going to do with this image... Since it's our first `init` release, we can start without a subscription manager and add it later if somebody really needs it. Alternatively, people can install it on top of our base image... Installing is better than removing imho.

**Review by srbala — APPROVED** [review]
Assuming @LKHN done necessarty in package list filter.
LGTM

**Pull request merged**
